### ISSUE TITLE
Fatal error: Uncaught phpfastcacheCoreException

### ISSUE THREAD

**Issue by xacknet** [level2-gis/gisapp#137]
Please help me solve the problem!! Windows server

Fatal error: Uncaught phpfastcacheCoreException: PLEASE CREATE OR CHMOD /var/tmp//localhost- - 0777 OR ANY WRITABLE PERMISSION! in C:\xampp\htdocs\gisapp\vendor\phpfastcache\phpfastcache\phpfastcache\3.0.0\phpfastcache.php:248 Stack trace: #0 C:\xampp\htdocs\gisapp\vendor\phpfastcache\phpfastcache\phpfastcache\3.0.0\abstract.php(459): phpFastCache::getPath(false, Array) #1 C:\xampp\htdocs\gisapp\vendor\phpfastcache\phpfastcache\phpfastcache\3.0.0\drivers\files.php(18): BasePhpFastCache->getPath() #2 C:\xampp\htdocs\gisapp\vendor\phpfastcache\phpfastcache\phpfastcache\3.0.0\phpfastcache.php(52): phpfastcache_files->__construct(Array) #3 C:\xampp\htdocs\gisapp\admin\class.Helpers.php(23): phpFastCache('files', Array) #4 C:\xampp\htdocs\gisapp\index.php(226): GisApp\Helpers->__construct() #5 {main} thrown in C:\xampp\htdocs\gisapp\vendor\phpfastcache\phpfastcache\phpfastcache\3.0.0\phpfastcache.php on line 248

**Comment by uprel** [comment]
I think you need to look at your settings.php file and adjust this line to working and writable directory

`define('TEMP_PATH', 'C:/Windows/Temp/');`
